# Production overrides for astraeus-oms
replicaCount: 2

image:
  pullPolicy: Always

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/astraeus-prod-oms

resources:
  requests:
    cpu: "1"
    memory: 2Gi
  limits:
    cpu: "2"
    memory: 4Gi

rollout:
  enabled: true
  strategy: blueGreen
  blueGreen:
    autoPromotionEnabled: false
    previewReplicaCount: 2
    scaleDownDelaySeconds: 600
