{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "astraeus-web.fullname" . }}
  labels:
    {{- include "astraeus-web.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      {{- include "astraeus-web.selectorLabels" . | nindent 6 }}
  strategy:
    canary:
      {{- range .Values.rollout.canary.steps }}
      steps:
        {{- if .setWeight }}
        - setWeight: {{ .setWeight }}
        {{- end }}
        {{- if .pause }}
        - pause:
            duration: {{ .pause.duration }}
        {{- end }}
      {{- end }}
      trafficRouting:
        nginx:
          stableIngress: {{ include "astraeus-web.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "astraeus-web.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "astraeus-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: next-cache
              mountPath: /app/.next/cache
      volumes:
        - name: next-cache
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
