"""Astraeus shared DTOs."""

from astraeus_contracts.health import (
    HealthResponse,
    HealthStatus,
    ReadinessCheck,
    ReadinessResponse,
    VersionResponse,
)
from astraeus_contracts.marketdata import (
    SCHEMA_REGISTRY,
    AssetClass,
    BarEvent,
    CorporateActionEvent,
    CorporateActionType,
    DataSource,
    DLQEvent,
    FundamentalEvent,
    MacroEvent,
    Resolution,
    TickEvent,
    get_schema_for_topic,
    validate_event,
)
from astraeus_contracts.portfolio import (
    AttributionResult,
    ClusterReport,
    ConstraintDiag,
    CovarianceMethod,
    FailedCheck,
    FallbackAction,
    OptimizerType,
    PortfolioStatus,
    PortfolioWeight,
    RiskRejection,
    RiskReport,
    ScenarioName,
    ScenarioResult,
    TargetPortfolio,
)
from astraeus_contracts.problem import ProblemDetails
from astraeus_contracts.signals import SignalEvent
from astraeus_contracts.topics import (
    bar_topic,
    corporate_action_topic,
    dlq_topic,
    fundamentals_topic,
    macro_topic,
    tick_topic,
)

__all__ = [
    "AttributionResult",
    "ClusterReport",
    "ConstraintDiag",
    "CovarianceMethod",
    "DLQEvent",
    "DataSource",
    "FailedCheck",
    "FallbackAction",
    "FundamentalEvent",
    "HealthResponse",
    "HealthStatus",
    "MacroEvent",
    "OptimizerType",
    "PortfolioStatus",
    "PortfolioWeight",
    "ProblemDetails",
    "ReadinessCheck",
    "ReadinessResponse",
    "Resolution",
    "RiskRejection",
    "RiskReport",
    "SCHEMA_REGISTRY",
    "ScenarioName",
    "ScenarioResult",
    "SignalEvent",
    "TargetPortfolio",
    "AssetClass",
    "BarEvent",
    "CorporateActionEvent",
    "CorporateActionType",
    "TickEvent",
    "VersionResponse",
    "bar_topic",
    "corporate_action_topic",
    "dlq_topic",
    "fundamentals_topic",
    "get_schema_for_topic",
    "macro_topic",
    "tick_topic",
    "validate_event",
]
